In [1]:
import numpy as np
from scipy import stats
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel

/Users/gyg/anaconda/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
print sm.datasets.spector.NOTE

::

    Number of Observations - 32

    Number of Variables - 4

    Variable name definitions::

        Grade - binary variable indicating whether or not a student's grade
                improved.  1 indicates an improvement.
        TUCE  - Test score on economics test
        PSI   - participation in program
        GPA   - Student's grade point average



In [3]:
data = sm.datasets.spector.load_pandas()
exog = sm.add_constant(data.exog, prepend=True)
endog = data.endog

In [4]:
sm_probit = sm.Probit(endog, exog).fit()

Optimization terminated successfully.
         Current function value: 0.400588
         Iterations 6


In [5]:
class MyProbit(GenericLikelihoodModel):
    def loglike(self, params):
        exog = self.exog
        endog = self.endog
        q = 2 * endog - 1
        return stats.norm.logcdf(q*np.dot(exog, params)).sum()

In [6]:
my_probit = MyProbit(endog, exog).fit()

Optimization terminated successfully.
         Current function value: 0.400588
         Iterations: 292
         Function evaluations: 494


In [7]:
print sm_probit.params

const   -7.452320
GPA      1.625810
TUCE     0.051729
PSI      1.426332
dtype: float64


In [8]:
print sm_probit.cov_params()

          const       GPA      TUCE       PSI
const  6.464166 -1.169668 -0.101173 -0.594792
GPA   -1.169668  0.481473 -0.018914  0.105439
TUCE  -0.101173 -0.018914  0.007038  0.002472
PSI   -0.594792  0.105439  0.002472  0.354070


In [9]:
print my_probit.params

[-7.45233176  1.62580888  0.05172971  1.42631954]


In [10]:
print my_probit.cov_params()

[[  6.46416770e+00  -1.16966617e+00  -1.01173181e-01  -5.94789009e-01]
 [ -1.16966617e+00   4.81472117e-01  -1.89134591e-02   1.05438228e-01]
 [ -1.01173181e-01  -1.89134591e-02   7.03758403e-03   2.47189233e-03]
 [ -5.94789009e-01   1.05438228e-01   2.47189233e-03   3.54069514e-01]]
